version: "3"
services:
  broker:
    image: broker
    command: /bin/sh -c "bin/broker"
    ports:
      - 5555:5555
    networks:
      - inter-judge-net
    deploy:
      mode: replicated
      replicas: 1

  file_provider:
    image: file_provider
    volumes:
      - /etc/hostname:/etc/hostname
      - /var/local/InterJudgeVolume:/inter-judge
    command: /bin/sh -c "bin/file_provider --provider_name=`cat /etc/hostname | tr -d '\n'` --logtostderr=1"
    networks:
      - inter-judge-net
    deploy:
      mode: replicated
      replicas: 20

  compiler_gpp:
    image: compiler_gpp
    volumes:
      - /etc/hostname:/etc/hostname
      - /var/local/InterJudgeVolume:/inter-judge
    command: /bin/sh -c "bin/compiler_gpp --file_provider=`cat /etc/hostname | tr -d '\n'` --logtostderr=1"
    networks:
      - inter-judge-net
    deploy:
      mode: replicated
      replicas: 10

  tester:
    image: tester
    volumes:
      - /etc/hostname:/etc/hostname
      - /var/local/InterJudgeVolume:/inter-judge
    command: /bin/sh -c "bin/tester --file_provider=`cat /etc/hostname | tr -d '\n'` --logtostderr=1"
    networks:
      - inter-judge-net
    deploy:
      mode: replicated
      replicas: 10

networks:
  inter-judge-net:
    driver: overlay
